const wordList = [
    { word: "antibiotic", hint: "A medicine used to treat bacterial infections." },
    { word: "anemia", hint: "A condition marked by a deficiency of red blood cells." },
    { word: "bronchitis", hint: "Inflammation of the lining of your bronchial tubes." },
    { word: "cholesterol", hint: "A waxy substance found in the blood." },
    { word: "diabetes", hint: "A disease that occurs when blood sugar is too high." },
    { word: "endoscopy", hint: "A procedure to look inside the body using a camera." },
    { word: "fracture", hint: "A break in the continuity of a bone." },
    { word: "gastritis", hint: "Inflammation of the stomach lining." },
    { word: "hemoglobin", hint: "The protein in red blood cells that carries oxygen." },
    { word: "immunology", hint: "The study of the immune system and immune responses." },
    { word: "jaundice", hint: "Yellowing of the skin due to liver disease or blood disorders." },
    { word: "kidney", hint: "An organ that filters waste from the blood." },
    { word: "leukemia", hint: "Cancer of the body's blood-forming tissues." },
    { word: "malignant", hint: "A term used to describe a severe and progressively worsening disease, especially cancer." },
    { word: "neurosurgery", hint: "Surgery involving the nervous system, especially the brain and spinal cord." },
    { word: "osteoporosis", hint: "A condition where bones become weak and brittle." },
    { word: "pediatrics", hint: "The branch of medicine dealing with children and their diseases." },
    { word: "quarantine", hint: "A period of isolation to prevent the spread of disease." },
    { word: "radiology", hint: "The use of medical imaging to diagnose and treat diseases." },
    { word: "sclerosis", hint: "Hardening of body tissues due to disease." },
    { word: "tachycardia", hint: "A faster than normal heart rate." },
    { word: "ultrasound", hint: "Imaging technique using sound waves to visualize internal body structures." },
    { word: "vaccine", hint: "A substance that stimulates the immune system to protect against diseases." },
    { word: "xenograft", hint: "A transplant of tissue from one species to another." },
    { word: "yellow fever", hint: "A viral infection transmitted by mosquitoes." },
    { word: "zoster", hint: "A viral infection causing a painful rash, also known as shingles." },
    { word: "allergy", hint: "A reaction by the immune system to a normally harmless substance." },
    { word: "biopsy", hint: "A diagnostic procedure that involves sampling tissue to check for disease." },
    { word: "concussion", hint: "A brain injury caused by a blow to the head." },
    { word: "dementia", hint: "A group of symptoms affecting memory, thinking, and social abilities." },
    { word: "eczema", hint: "A condition that causes the skin to become red, itchy, and inflamed." },
    { word: "fibrillation", hint: "A rapid and irregular heart rate." },
    { word: "glucose", hint: "A type of sugar used by the body for energy." },
    { word: "herpes", hint: "A viral infection that causes sores, often on the mouth or genitals." },
    { word: "incision", hint: "A surgical cut made to access the inside of the body." },
    { word: "joints", hint: "The connections between two bones in the body." },
    { word: "ketosis", hint: "A metabolic state where fat is used for energy instead of carbohydrates." },
    { word: "laceration", hint: "A deep cut or tear in the skin." },
    { word: "mammogram", hint: "An X-ray picture of the breast." },
    { word: "nephrology", hint: "The study of the kidneys and their diseases." },
    { word: "obstetrics", hint: "The branch of medicine that deals with pregnancy and childbirth." },
    { word: "pneumonia", hint: "An infection that inflames the air sacs in the lungs." },
    { word: "quinsy", hint: "A painful abscess near the tonsils, usually caused by tonsillitis." },
    { word: "respiration", hint: "The process of inhaling and exhaling air to exchange oxygen and carbon dioxide." },
    { word: "sepsis", hint: "A life-threatening condition caused by the body's response to infection." },
    { word: "tuberculosis", hint: "A bacterial infection that mainly affects the lungs." },
    { word: "urticaria", hint: "A skin condition commonly known as hives." },
    { word: "varicose", hint: "Enlarged, swollen veins often seen in the legs." },
    { word: "wound", hint: "An injury that breaks the skin or other body tissue." },
    { word: "xerostomia", hint: "A condition commonly known as dry mouth." },
    { word: "zoology", hint: "The study of animals and their biology." },
    { word: "abscess", hint: "A collection of pus that has built up within the tissue of the body." },
    { word: "bacteria", hint: "Single-celled microorganisms that can cause disease." },
    { word: "cholecystitis", hint: "Inflammation of the gallbladder." },
    { word: "diarrhea", hint: "Frequent, watery bowel movements." },
    { word: "esophagus", hint: "The tube that carries food from the mouth to the stomach." },
    { word: "fibrosis", hint: "Thickening or scarring of connective tissue." },
    { word: "gallstones", hint: "Hardened deposits in the gallbladder." },
    { word: "hepatitis", hint: "Inflammation of the liver." },
    { word: "insulin", hint: "A hormone that regulates blood sugar levels." },
    { word: "joints", hint: "The points where two bones meet." },
    { word: "keloid", hint: "A thick, raised scar formed after an injury." },
    { word: "lupus", hint: "An autoimmune disease that attacks healthy tissue." },
    { word: "metastasis", hint: "The spread of cancer cells to new areas of the body." },
    { word: "nausea", hint: "A feeling of discomfort that often leads to vomiting." },
    { word: "osteotomy", hint: "Surgical cutting of bone." },
    { word: "prognosis", hint: "The likely course of a disease or ailment." },
    { word: "quadriplegia", hint: "Paralysis of all four limbs." },
    { word: "radiation", hint: "Energy emitted as waves or particles, used in cancer treatment." },
    { word: "sarcoma", hint: "A type of cancer that occurs in bones and soft tissues." },
    { word: "tendon", hint: "A tissue that connects muscle to bone." },
    { word: "ulcer", hint: "A sore on the skin or a mucous membrane." },
    { word: "vein", hint: "A blood vessel that carries blood toward the heart." },
    { word: "wart", hint: "A small growth caused by a viral infection of the skin." },
    { word: "x-ray", hint: "A diagnostic tool that uses radiation to create images of the inside of the body." },
    { word: "zygote", hint: "A fertilized egg cell." },
    { word: "anorexia", hint: "An eating disorder characterized by an intense fear of gaining weight." },
    { word: "bursitis", hint: "Inflammation of the fluid-filled sacs that cushion joints." },
    { word: "cataract", hint: "A cloudy area in the lens of the eye." },
    { word: "dialysis", hint: "A medical procedure that removes waste products from the blood when the kidneys fail." },
    { word: "edema", hint: "Swelling caused by excess fluid trapped in the body's tissues." },
    { word: "fistula", hint: "An abnormal connection between two body parts." },
    { word: "gangrene", hint: "Death of tissue caused by a lack of blood supply or infection." },
    { word: "hernia", hint: "A condition in which an organ pushes through the muscle or tissue that holds it in place." },
    { word: "ischemia", hint: "An inadequate blood supply to an organ or part of the body." },
    { word: "jaundice", hint: "Yellowing of the skin and eyes due to liver problems." },
    { word: "kyphosis", hint: "Excessive outward curvature of the spine, causing hunching}." }]
